# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers every day, at 4:00 UTC time.
  schedule:
  - cron: "0 4 * * *"

  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Download cn.txt file
        run: wget https://raw.githubusercontent.com/Loyalsoldier/geoip/refs/heads/release/surge/cn.txt -O cn.txt

      - name: Download gfw.txt file
        run: wget https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt -O gfw.txt

      - name: convert into noncn.json and gfw.json
        run: python3 convert.py

      - name: Download and extract singbox 1.10.1
        run:
          wget https://github.com/SagerNet/sing-box/releases/download/v1.10.1/sing-box-1.10.1-linux-amd64.tar.gz -O - | tar -zxf - -C ./

      - name: Convert json files to SRS files
        run: |
          ./sing-box-1.10.1-linux-amd64/sing-box rule-set compile --output noncn.srs noncn.json
          ./sing-box-1.10.1-linux-amd64/sing-box rule-set compile --output gfw.srs gfw.json

      - name: Get current time
        id: time
        run: echo "time=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.time.outputs.time }}
          tag_name: ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
          make_latest: true
          files: |
            noncn.json
            gfw.json
            noncn.srs
            gfw.srs

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
